name: 3 Config Env Variables

on:
  workflow_dispatch:
  
env:
  FUNCTION_NAME: oalogsfunc-12345
  AZURE_RG: SP-PoC_Zone
  API_ID: ${{ secrets.API_ID }}
  API_KEY: ${{ secrets.API_KEY }}
  TENANT_ID: ${{ secrets.TENANT_ID }}
  WORKSPACE_ID: ${{ secrets.WORKSPACE_ID }}
  DAYS: 1
  QUERY: 'AppRequests | summarize CountByCountry=count() by ClientCountryOrRegion | top 10 by CountByCountry'
  
  

jobs:
  config-env-variables:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Config Env Variables
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az functionapp config appsettings set --name ${{ env.FUNCTION_NAME }}  --resource-group ${{ env.AZURE_RG }} --settings API_ID=${{ env.API_ID }} API_KEY=${{ env.API_KEY }} TENANT_ID=${{ env.TENANT_ID }} WORKSPACE_ID=${{ env.WORKSPACE_ID }}
